# Site settings
title: My old Blog on LinkedIn
author name: Priyanshu Mishra
  email: mpriyanshu236@gmail.com
description: "Learning to create great site using Jekyll on GH-Pages."

# Build settings
remote_theme: jekyll/minima
